repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
    -   id: ruff
        args: ["--fix", "--output-format=full"]
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.9.0
#     hooks:
#      -  id: mypy
#         files: nxlu/
#         additional_dependencies: [pytest==6.2.4]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
    -   id: prettier
        files: ^doc/scss/|^doc/js/scripts/
        exclude: ^doc/js/scripts/vendor/
        types_or: ["scss", "javascript"]
