algorithms:
  - name: "average_clustering"
    func: "networkx.average_clustering"
    params: {}
    requires_directed: false
    groups: ["clustering", "graph_structure"]
    validate_result: "nxbench.validation.validate_scalar_result"

  - name: "pagerank"
    func: "networkx.pagerank"
    params:
      alpha: 0.9
      tol: 1.0e-6
    requires_directed: false
    groups: ["centrality", "random_walk"]

  - name: "eigenvector_centrality"
    func: "networkx.eigenvector_centrality"
    params:
      max_iter: 500
      tol: 1e-06
    requires_directed: false
    groups: ["centrality", "path_based"]
    validate_result: "nxbench.validation.validate_node_scores"

datasets:
  - name: "erdos_renyi_small"
    source: "generator"
    params:
      generator: "networkx.erdos_renyi_graph"
      n: 1000
      p: 0.01
    metadata:
      directed: false
      weighted: false

validation:
  skip_slow: false
  validate_all: true
  error_on_fail: true
  report_memory: true

environ:
  backend:
    networkx:
      - "networkx==3.4.1"
    graphblas:
      - "graphblas_algorithms==2023.10.0"
  num_threads:
    - "1"
    - "4"
    - "8"
  pythons:
    - "3.10"
