algorithms:
  - name: "average_clustering"
    func: "networkx.average_clustering"
    params: {}
    requires_directed: false
    groups: ["clustering", "graph_structure"]
    min_rounds: 3
    validate_result: "nxbench.validation.validate_scalar_result"

datasets:
  # - name: "erdos_renyi_small"
  #   source: "generator"
  #   params:
  #     generator: "networkx.erdos_renyi_graph"
  #     n: 1000
  #     p: 0.01
  #   metadata:
  #     directed: false
  #     weighted: false

  # - name: "enron"
  #   source: "networkrepository"
  #   params: {}

  # - name: "citationCiteseer"
  #   source: "networkrepository"
  #   params: {}

  - name: "patentcite"
    source: "networkrepository"
    params: {}

  # - name: "ca-netscience"
  #   source: "networkrepository"
  #   params: {}

validation:
  skip_slow: false
  validate_all: true
  error_on_fail: true
  report_memory: true

matrix:
  backend:
    - "networkx"
    - "graphblas"
  num_threads:
    - "1"

env_config:
  req:
    - "networkx==3.4.2"
    - "nx-parallel-0.3rc0.dev0"
    - "graphblas_algorithms==2023.10.0"
  pythons:
    - "3.10"
    - "3.11"
