algorithms:
  - name: "pagerank"
    func: "networkx.pagerank"
    params:
      alpha: 0.9
      tol: 1.0e-6
    requires_directed: false
    groups: ["centrality", "random_walk"]

  - name: "eigenvector_centrality"
    func: "networkx.eigenvector_centrality"
    params:
      max_iter: 500
      tol: 1e-06
    requires_directed: false
    groups: ["centrality", "path_based"]
    validate_result: "nxbench.validation.validate_node_scores"

  # - name: "betweenness_centrality"
  #   func: "networkx.betweenness_centrality"
  #   params:
  #     normalized: true
  #     endpoints: false
  #   requires_directed: false
  #   groups: ["centrality", "path_based"]
  #   min_rounds: 5
  #   warmup: true
  #   warmup_iterations: 20
  #   validate_result: "nxbench.validation.validate_node_scores"

  # - name: "edge_betweenness_centrality"
  #   func: "networkx.edge_betweenness_centrality"
  #   params:
  #     normalized: true
  #   requires_directed: false
  #   groups: ["centrality", "path_based"]
  #   min_rounds: 5
  #   warmup: true
  #   warmup_iterations: 20
  #   validate_result: "nxbench.validation.validate_edge_scores"

  # - name: "approximate_all_pairs_node_connectivity"
  #   func: "networkx.algorithms.approximation.connectivity.all_pairs_node_connectivity"
  #   params: {}
  #   requires_directed: false
  #   groups: ["connectivity", "approximation"]
  #   min_rounds: 3

  - name: "average_clustering"
    func: "networkx.average_clustering"
    params: {}
    requires_directed: false
    groups: ["clustering", "graph_structure"]
    validate_result: "nxbench.validation.validate_scalar_result"

  - name: "square_clustering"
    func: "networkx.square_clustering"
    params: {}
    requires_directed: false
    groups: ["clustering", "graph_structure"]
    validate_result: "nxbench.validation.validate_node_scores"

  - name: "transitivity"
    func: "networkx.transitivity"
    params: {}
    requires_directed: false
    groups: ["clustering", "graph_structure"]
    validate_result: "nxbench.validation.validate_scalar_result"

  # - name: "all_pairs_node_connectivity"
  #   func: "networkx.algorithms.connectivity.connectivity.all_pairs_node_connectivity"
  #   params: {}
  #   requires_directed: false
  #   groups: ["connectivity", "paths"]

  # - name: "local_efficiency"
  #   func: "networkx.local_efficiency"
  #   params: {}
  #   requires_directed: false
  #   groups: ["efficiency", "graph_measure"]
  #   validate_result: "nxbench.validation.validate_node_scores"

  - name: "number_of_isolates"
    func: "networkx.number_of_isolates"
    params: {}
    requires_directed: false
    groups: ["isolates", "graph_measure"]

  # - name: "all_pairs_all_shortest_paths"
  #   func: "networkx.all_pairs_all_shortest_paths"
  #   params:
  #     weight: "weight"
  #   requires_directed: false
  #   groups: ["paths", "all_pairs"]

  # - name: "all_pairs_shortest_path_length"
  #   func: "networkx.all_pairs_shortest_path_length"
  #   params: {}
  #   requires_directed: false
  #   groups: ["paths", "distance"]
  #   validate_result: "nxbench.validation.validate_scalar_result"

  # - name: "all_pairs_shortest_path"
  #   func: "networkx.all_pairs_shortest_path"
  #   params: {}
  #   requires_directed: false
  #   groups: ["paths", "distance"]

  # - name: "all_pairs_dijkstra"
  #   func: "networkx.all_pairs_dijkstra"
  #   params:
  #     weight: "weight"
  #   requires_directed: false
  #   groups: ["paths", "weighted"]

  - name: "all_pairs_dijkstra_path_length"
    func: "networkx.all_pairs_dijkstra_path_length"
    params:
      weight: "weight"
    requires_directed: false
    groups: ["paths", "weighted"]
    validate_result: "nxbench.validation.validate_scalar_result"

  - name: "all_pairs_bellman_ford_path_length"
    func: "networkx.all_pairs_bellman_ford_path_length"
    params:
      weight: "weight"
    requires_directed: false
    groups: ["paths", "weighted"]
    validate_result: "nxbench.validation.validate_scalar_result"

  # - name: "johnson"
  #   func: "networkx.johnson"
  #   params:
  #     weight: "weight"
  #   requires_directed: false
  #   groups: ["paths", "weighted"]

  # - name: "closeness_vitality"
  #   func: "networkx.closeness_vitality"
  #   params: {}
  #   requires_directed: false
  #   groups: ["vitality", "centrality"]

datasets:
  # - name: "enron"
  #   source: "networkrepository"
  #   params: {}

  # - name: "citationCiteseer"
  #   source: "networkrepository"
  #   params: {}

  # - name: "karate"
  #   source: "networkrepository"
  #   params: {}

  # - name: "patentcite"
  #   source: "networkrepository"
  #   params: {}

  - name: "erdos_renyi_small"
    source: "generator"
    params:
      generator: "networkx.erdos_renyi_graph"
      n: 1000
      p: 0.01
    metadata:
      directed: false
      weighted: false

  - name: "erdos_renyi_small"
    source: "generator"
    params:
      generator: "networkx.erdos_renyi_graph"
      n: 1000
      p: 0.01
    metadata:
      directed: true
      weighted: false

  - name: "watts_strogatz_small"
    source: "generator"
    params:
      generator: "networkx.watts_strogatz_graph"
      n: 1000
      k: 6
      p: 0.1
    metadata:
      directed: false
      weighted: false

  - name: "watts_strogatz_small"
    source: "generator"
    params:
      generator: "networkx.watts_strogatz_graph"
      n: 1000
      k: 6
      p: 0.1
    metadata:
      directed: false
      weighted: true

  # - name: "barabasi_albert_small"
  #   source: "generator"
  #   params:
  #     generator: "networkx.barabasi_albert_graph"
  #     n: 1000
  #     m: 3
  #   metadata:
  #     directed: false
  #     weighted: false

  # - name: "powerlaw_cluster_small"
  #   source: "generator"
  #   params:
  #     generator: "networkx.powerlaw_cluster_graph"
  #     n: 1000
  #     m: 2
  #     p: 0.1
  #   metadata:
  #     directed: false
  #     weighted: false

  # - name: "erdos_renyi_large"
  #   source: "generator"
  #   params:
  #     generator: "networkx.erdos_renyi_graph"
  #     n: 10000
  #     p: 0.01
  #   metadata:
  #     directed: false
  #     weighted: false

  # - name: "watts_strogatz_large"
  #   source: "generator"
  #   params:
  #     generator: "networkx.watts_strogatz_graph"
  #     n: 10000
  #     k: 6
  #     p: 0.1
  #   metadata:
  #     directed: false
  #     weighted: false

  # - name: "barabasi_albert_large"
  #   source: "generator"
  #   params:
  #     generator: "networkx.barabasi_albert_graph"
  #     n: 10000
  #     m: 3
  #   metadata:
  #     directed: false
  #     weighted: false

  # - name: "powerlaw_cluster_large"
  #   source: "generator"
  #   params:
  #     generator: "networkx.powerlaw_cluster_graph"
  #     n: 10000
  #     m: 2
  #     p: 0.1
  #   metadata:
  #     directed: false
  #     weighted: false

validation:
  skip_slow: false
  validate_all: true
  error_on_fail: true
  report_memory: true

environ:
  backend:
    networkx:
      - "networkx==3.4.1"
      - "networkx==3.4.2"
    graphblas:
      - "graphblas_algorithms==2023.10.0"
  num_threads:
    - "1"
    - "4"
    - "8"
  pythons:
    - "3.10"
    - "3.11"
