# name: Build and Deploy to PyPI

# on:
#   push:
#     tags:
#       - 'v*.*.*'
#   repository_dispatch:
#     types: [deploy-pypi]

# jobs:
#   build-and-deploy:
#     name: Build and Deploy to PyPI
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Cache pip
#         uses: actions/cache@v4
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip setuptools wheel twine
#           pip install -U build

#       - name: Build Package
#         run: |
#           python -m build --sdist --wheel

#       - name: Publish to PyPI
#         uses: pypa/gh-action-pypi-publish@v1.4.2
#         with:
#           user: __token__
#           password: ${{ secrets.PYPI_API_TOKEN }}
#         env:
#           TWINE_USERNAME: __token__
#           TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
