# name: Release

# on:
#   push:
#     branches:
#       - main

# jobs:
#   bump-version-and-tag:
#     name: Bump Version and Create Tag
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install bump2version

#       - name: Configure Git user
#         run: |
#           git config --global user.email "nxbench.bot@gmail.com"
#           git config --global user.name "nxbench bot"

#       - name: Bump Version
#         run: |
#           bump2version patch --allow-dirty

#       - name: Push Changes and Tags
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           branch: main
#           tags: true

#       - name: Trigger PyPI Deployment
#         uses: peter-evans/repository-dispatch@v2
#         with:
#           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           event-type: deploy-pypi
